check links

1. https://github.com/dongxiexidu/changeSkinColor  - change skin
2. https://github.com/weishine121/ChangeSkinColor - skin
3. https://github.com/nonoBruce/ImageColorChange - image color change
4. https://github.com/ShengHuaWu/SHDrawSimpleImage  - change
5. https://github.com/delarge77/ADColorImage  - c2

1. https://github.com/udspj/DarkSIBARICropImage  - check 
2. https://github.com/SushreeSwagatika/SSImageEditor - ck2
3. https://github.com/XUEXi/XXImagePicker ck3


