check links

1. https://github.com/dongxiexidu/changeSkinColor  - change skin
2. https://github.com/weishine121/ChangeSkinColor - skin
3. https://github.com/nonoBruce/ImageColorChange - image color change
4. https://github.com/ShengHuaWu/SHDrawSimpleImage  - change
5. https://github.com/delarge77/ADColorImage  - c2

1. https://github.com/udspj/DarkSIBARICropImage  - check 
2. https://github.com/SushreeSwagatika/SSImageEditor - ck2
3. https://github.com/XUEXi/XXImagePicker ck3

1. https://github.com/JasonSparrow/BeautyImage - ck4
2. https://github.com/mingway1991/BeautyFace ck5
3. https://github.com/nonoBruce/ImageColorChange - ck6n

1. https://github.com/Maru-zhang/MARFaceBeauty  ck

2.https://github.com/mingway1991/BeautyFace - ck2

3. https://github.com/JasonSparrow/BeautyImage ck

1. https://stackoverflow.com/questions/5145953/how-to-tint-an-image-show-a-colour 
2. blackOverlay.layer.opacity = 0.3f;  try set like this imageview opacity
3. https://stackoverflow.com/questions/16257379/color-overlay-on-specific-area-of-uiimage 



